const categories = [
    'Types of Ice Cream',
    'Countries in Europe',
    'US States',
    'Fruits',
    'Animals',
    'Famous Paintings',
    'World Capitals',
    'Car Brands',
    'Mathematical Concepts',
    'Programming Languages',
    'Historical Events',
    'Famous Authors',
    'Chemical Elements',
    'Astronomy Terms',
    'Musical Instruments',
    'Olympic Sports',
    'Movie Genres',
    'Types of Cuisine',
    'Board Games',
    'Mythological Creatures',
    'Computer Parts',
    'Novel Genres',
    'Types of Dance',
    'World Rivers',
    'Famous Landmarks',
    'Types of Birds',
    'Types of Fish',
    'Types of Flowers',
    'Types of Trees',
    'Types of Rocks',
    'Types of Clouds',
    'Types of Insects',
    'Types of Reptiles',
    'Types of Mammals',
    'Types of Bacteria',
    'Types of Fungi',
    'Types of Viruses',
    'Types of Diseases',
    'Types of Medicines',
    'Types of Surgeries',
    'Types of Doctors',
    'Types of Engineers',
    'Types of Scientists',
    'Types of Teachers',
    'Types of Lawyers',
    'Types of Politicians',
    'Types of Artists',
    'Types of Writers',
    'Types of Musicians',
    'Types of Actors'
];
module.exports = categories;